### ISSUE TITLE
tmuxp CLA

### ISSUE THREAD

**Issue by tony** [timgates42/meticulous#142]
In re: https://github.com/tmux-python/tmuxp/pull/785

I'm wondering if you don't get notifications for the PRs being filed, but I'm happy to merge your contribution if you sign the CLA 😃

**Comment by timgates42** [comment]
Thanks I do - but unfortunately its quite common for me to miss a notification here and there - thanks for the follow up.

**Comment by tony** [comment]
@timgates42 Thank you! Merged in https://github.com/tmux-python/tmuxp/commit/33817595ca6ab1d3a29811feb08e007c5dffb9ab!
