### ISSUE TITLE
meticulous shouldn't create an issue *and* a pull request

### ISSUE THREAD

**Issue by martey** [timgates42/meticulous#55]
If a repository has both issues and pull requests enabled, meticulous allows users the option to create both an issue and a pull request. Anyone watching the repository is notified twice.

I think meticulous to default to only creating a pull request. Typos are generally quick fixes, and many repositories don't require (or want) issues that will be immediately fixed by a pull request.

It's possible that there are repositories that require all pull request to reference an existing issue (necessitating the creation of both). I would posit that these are in the minority, and that meticulous could still allow users to do both after a sufficient warning.

**Comment by timgates42** [comment]
Thanks @martey - good point - I’ll add PR to default to just a PR with the option of adding an issue if required in the contribution guidelines

**Comment by timgates42** [comment]
Thanks @martey I've made submitting a PR the first option in the menu in PR #61 - users can still select to create an issue if required in the contributors guide.
